### ISSUE TITLE
insert None to DEFAULT defined column error

### ISSUE THREAD

**Issue by xiongyifan** [ClickHouse/clickhouse-connect#100]
here is the table.

```SQL
CREATE TABLE stock_list (code String, list_date Date, delist_date Date DEFAULT toDate('1970-01-01')) ENGINE ReplacingMergeTree ORDER BY code
```

not work, if None is here.

```python
client.insert('stock_list', [['000001', pd.to_datetime('2019-10-10'), None]])
```

work, None is not here. And the `delist_date` value is the default value `1970-01-01` in the table. 

```python
client.insert('stock_list_tushare', [['000001', pd.to_datetime('2019-10-10')]], column_names=['code', 'list_date'])
```

`client.insert_df` has the same problem. None and pd.NaT does not work.

is there any mistake in the code?

**Comment by genzgd** [comment]
Currently ClickHouse Connect treats a Python `None` as a ClickHouse `NULL`, so if you actually want to insert `NULL` into the `delist_date` column you must declare that column `Nullable(Date)` instead.

However I assume that you want the `None` insert to instead insert the ClickHouse DEFAULT value of '1970-01-01'.  Unfortunately that approach doesn't work in ClickHouse Connect or other ClickHouse clients that use the Native protocol for inserts (such as `clickhouse-go` or `clickhouse-driver`).  The Native protocol has no way to specify `DEFAULT` or `NULL` as the value in a non-null column.

To work around that you could insert only the columns with non-default values:

```python
client.insert('stock_list', [['000001', pd.to_datetime('2019-10-10')]], ['code', 'list_date'])
```

Otherwise you must convert the `None` values in your data to your desired default before calling the `insert` method.

If there is enough interest we could add an enhancement that automatically reads the column default and converts `None` values to that default before insert, but the only advantage would be convenience.  The work of changing every `None` to the default would still be in the Python client.

**Comment by genzgd** [comment]
Sorry, re-reading your question it looks like you do just want NULL in the column.  As a reminder, all ClickHouse columns are not nullable by default.  So the answer is just:

```sql
CREATE TABLE stock_list (code String, list_date Date, delist_date Nullable(Date)) ENGINE ReplacingMergeTree ORDER BY code
```

**Comment by xiongyifan** [comment]
thank for you fast response. you are right, I want to the default '1970-01-01', because of the Best Practices [avoid-nullable-columns](https://clickhouse.com/docs/en/cloud/bestpractices/avoid-nullable-columns/) .

I tried to fill None, It works.

```python
data['delist_date'] = data['delist_date'].fillna(pd.to_datetime('1970-01-01'))
client.insert_df("stock_list", data)
```

It's kind of weird. I set the DEFAULT, but in clickhouse-connect is not work. 
So I tried in sql, and it works.
```SQL
insert into stock_list values ('000001', toDate('2019-10-10'), NULL)
```

If there is a `doc` about it, that is grest.

**Comment by genzgd** [comment]
Yes if you use direct SQL it will work because the full text of the SQL `INSERT` query is sent directly to ClickHouse (it does not use the native protocol).  ClickHouse will convert NULL to the DEFAULT based on the setting `insert_null_as_default` which is normally set to `1`.

 Unfortunately like I said that approach doesn't work with `Native` format inserts used by ClickHouse Connect for inserting multiple rows of data.

I don't know of any doc that covers this particular issue, but we can look into creating one.

**Comment by xiongyifan** [comment]
now, I know how to do and understand the reason, because of your response. thanks a lot.
