### ISSUE TITLE
Incorrect DateTime values on applying timezone

### ISSUE THREAD

**Issue by rejochandran** [ClickHouse/clickhouse-connect#120]
clickhouse-connect does not take into account if timezone is specified in functions like `DateTime(<date>, <timezone)` and `toTimezone(<date>, <timezone)`

Consider this table:
```
CREATE TABLE default.tbl
(
    `id` UInt32,
    `created_date` Nullable(DateTime())
)
ENGINE = MergeTree
ORDER BY id
SETTINGS index_granularity = 8192
```

Adding some data...
```
INSERT INTO default.tbl VALUES (1,toDateTime('2017-08-04 06:09:00))
```

Querying through ClickHouse Play or Tabix:
```
SELECT toTimezone(created_date,'America/Chicago') AS created_date FROM default.tbl
```
Returns, different date, applying the timezone ✅
| created_date        |
|---------------------|
| 2017-08-04 01:09:00 | 

Querying through Clickhouse connect:

```
client = clickhouse_connect.get_client(...)
client.query_df(query="SELECT toTimezone(created_date,'America/Chicago') AS created_date FROM default.tbl")
```
Returns, without applying the timezone ❌
```
          created_date
0 2017-08-04 06:09:00
```

alternatives tried, but didnt work
1. Used custom `QueryContext` with different timezone from the QueryContext through `create_query_context(query=query_str).updated_copy()`
2. Tried editing the server_tz param in the `client` 

Environment:
Clickhouse version: 23.1.3.5
Clickhouse connect version: 0.5.7
the application runs in an Docker image

Any workarounds?

**Comment by genzgd** [comment]
After digging into this it looks like the underlying problem here is that the Native format over HTTP does not send any timezone information for the columns (apparently row binary doesn't either).  All that comes from the server is the "DateTime" type and an integer value for epoch seconds.  The native protocol (not Native format over HTTP) does provide this information so ClickHouse Client (and other native protocol based clients, such as clickhouse-go and the clickhouse-driver Python client) have that information available for processing.

Accordingly any workaround I think has to apply timezone information within the client itself, so it has to be available somehow during the query processing.  A short term workaround would be putting a `query_tz` property in the query_context, assuming that normally a single query won't need to handle multiple timezones.  Column specific timezones are probably possible in the QueryContext as well, so I can add that too.

I'm open to other suggestions (and I'll open an issue in ClickHouse about sending timezone information in the Native response), but I don't have a good answer right now other than providing additional timezone information when executing the query.

**Comment by genzgd** [comment]
New ClickHouse issue:  https://github.com/ClickHouse/ClickHouse/issues/46176

I was incorrect above about RowBinary -- using RowBinaryWithNamesAndTypes actually returns the full column type with timezone information.  I think that's how I missed this issue, my original implementation used the RowBinaryWithNamesAndTypes format and timezones worked with that (way back last year).  Unfortunately I didn't add tests for that :(

**Comment by rejochandran** [comment]
Thank you for the response!
As mentioned above, digging clickhouse-connect, I dont find a `query_tz` property in query_context.
if you ment `server_tz`, I already tried passing the timezone likewise but had the same response,

```
ctx = client.create_query_context(query_str).updated_copy(
    server_tz=pytz.timezone("Asia/Tel_Aviv")
)
```

Please let me know if I'm adding the right property

**Comment by genzgd** [comment]
Unfortunately these things don't exist yet -- adding `query_tz` and
`column_tz` arguments to the QueryContext is my current plan for working
around the fact that there's no way to get the timezone information from
the ClickHouse response.  It sounds like that would at least be helpful,
but I probably won't get to adding that feature until next week or so.

**Comment by rejochandran** [comment]
Thanks @genzgd! will follow this issue for updates 🙂

**Comment by genzgd** [comment]
Okay, 0.5.8 has been released with support for `query_tz` and `column_tzs` query keyword arguments that will be applied to DateTime (and DateTime64) datatypes.  A description of the workaround is in the [changelog](https://github.com/ClickHouse/clickhouse-connect/blob/main/CHANGELOG.md), and some very basic examples in the [test file](https://github.com/ClickHouse/clickhouse-connect/blob/main/tests/integration_tests/test_timezones.py).  I'm also working on a small documentation update for these parameters.

I'm leaving this issue open until we have a better fix for the underlying ClickHouse issue and can rely on ClickHouse to send back the timezone information with the query.

**Comment by genzgd** [comment]
@imartov, please include your ClickHouse server version, your clickhouse-connect version, and the timezone that your ClickHouse server uses.
