### ISSUE TITLE
Writing bytes to String column fails (INTERNAL EXCEPTION WHILE SERIALIZING)

### ISSUE THREAD

**Issue by TimNooren** [ClickHouse/clickhouse-connect#148]
Writing bytes to a `String` column fails with `INTERNAL EXCEPTION WHILE SERIALIZING`. Writing bytes to `FixedString` works as expected, so I assume the same should be possible with `String` columns. But I'm very new to Clickhouse, so I may have missed something:)

### Steps to reproduce
See https://github.com/ClickHouse/clickhouse-connect/compare/main...TimNooren:clickhouse-connect:string_accepts_bytes for a unit test that illustrates the issue, and a naive fix.

#### Environment
* clickhouse-connect version: 0.5.15
* Python version: 3.11.12
* Operating system: macOS (ARM)

**Comment by genzgd** [comment]
Thanks for opening this issue and taking the time to investigate a fix.  Accepting bytes for a string column makes perfect sense and I'm surprised no one has mentioned it before.  

My only concern with your fix is performance, since string writes are already slow and an extra type check and assignment are going to make that slightly worse.  But I can address that later as part of https://github.com/ClickHouse/clickhouse-connect/issues/106.  For a short term fix I'm inclined to use the same approach as other columns, and assume that all values in the column are the same type as the first (non-NULL) value and write all strings or all bytes objects as appropriate.

**Comment by TimNooren** [comment]
@genzgd Makes sense to at least use the same approach as for `FixedString`👍 Would be happy to submit a PR, but I see you already covered it. Thanks:)
