### ISSUE TITLE
Add docs section about parallelism (multi-processing)

### ISSUE THREAD

**Issue by rbeeli** [ClickHouse/clickhouse-connect#169]
It would be great to have some guidelines and dos/donts for parallel processing. I.e., can client instances be cached and shared across threads and/or processes, or what is the best practice? Each process instance must instantiate their own client?

There is the `session_id` client parameter, which can get auto-generated if not set, but I think parallel use of the same session is not allowed by ClickHouse, so intuitively, it would imply to create new client instances per process to avoid parallel use of same session.

Also, with parallel processing, the topic of performance and client instantiation overhead seems important:
How to use the client most efficiently in a parallel processing setup? Any recommendations on reducing client instantiation overhead?

**Comment by genzgd** [comment]
I haven't had a chance to update the docs with a session on parallelism, but I have intended to for quite some time.

In particular, you are correct about the implications of session_id and trying to use the same client in a multi-processing situation.  However, if you don't need to maintain a session, you can set the common setting `autogenerate_session_id` to false and reuse the same session.  The client is "close enough" to stateless that that should work fairly efficiently.  In combination with that you might want to create your own urllib3 PoolManager which allows more concurrent connections that the 8 used by default.

At the moment client instantiation is moderately expensive because the client executes two queries to the get the server version, timezone, and defaults database, as well as the system settings.  It would make sense to cache and reuse those values for the same server, so I'll look at adding something like that in the future.

**Comment by rbeeli** [comment]
If I set `autogenerate_session_id` to `false`, pass no `session_id`, and reuse the same client instance, in what scenarios would this lead to errors? Somewhere I read something about temporary tables, but not sure. Parallel reads and writes using the same client in multiprocessing are possible?

Since ClickHouse is all about performance, I think it's worth investigating this topic and extend the docs, even if it's just a couple of sentences to shed some light on it.

---

Unrelated comment: The Apache Arrow support is great, major performance boost compared to plain Python objects, especially for inserts! And with pandas 2 having an Arrow backend, it hopefully becomes a first-class citizen in many more projects.

**Comment by genzgd** [comment]
Docs updated in https://github.com/ClickHouse/clickhouse-docs/pull/1154
