### ISSUE TITLE
I hope that I can set timezone during create connect

### ISSUE THREAD

**Issue by campanulamediuml** [ClickHouse/clickhouse-connect#193]
**Is your feature request related to a problem? Please describe.**
Datetime string from sql query is UTC time but localtime is UTC+8:00, there is no params to config time zone in python connector

**Describe the solution you'd like**
I hope there will be a param in clickhouse_connect.get_client()  to set the timezone of data that I read

**Describe alternatives you've considered**
I use datetime.timedelta(hour=8)  in data i selected, and minus 8 hours when I'm using select query in my business code 

**Additional context**
No

**Comment by genzgd** [comment]
What timezone does your clickhouse server use?  If your clickhouse server is in the desired timezone you can use `apply_server_timezone='always'` when creating the client.

Are you using columns that have the timezone defined?  That will normally override the server timezone or the local timezone.

You ca also  pass a `query_tz` parameter to any of the query methods to have the result returned in the requested timezone.  

Finally you could set the timezone for your application, so that timezone naive datetime objects will be rendered in that timezone.  See the code in https://github.com/ClickHouse/clickhouse-connect/blob/main/tests/conftest.py:

```python
os.environ['TZ'] = 'Asia/Shanghai'
time.tzset()
```

Given all of these options I think adding an additional "client" timezone will just create more confusion?
