### ISSUE TITLE
`DateTime64` is cut at seconds value when supplied as a parameter

### ISSUE THREAD

**Issue by pkit** [ClickHouse/clickhouse-connect#212]
```python
client.query(
  "SELECT {t:DateTime64(3, 'UTC')}",
  parameters={"t": datetime.datetime(2023, 6, 28, 16, 54, 41, 714000, tzinfo=datetime.timezone.utc)},
).result_set
```
produces
```
[(datetime.datetime(2023, 6, 28, 16, 54, 41),)]
```
all the milliseconds are lost

Do I need to change my app and manually convert it to `UInt64` here too?

**Comment by genzgd** [comment]
You could convert your datetime parameter to a string using a format that ClickHouse recognizes instead of having clickhouse-connect trying to guess which format it needs.  Any datetime parameter object is converted using this code
```python
        if value.tzinfo is None and server_tz != local_tz:
            value = value.replace(tzinfo=server_tz)
        return f"'{value.strftime('%Y-%m-%d %H:%M:%S')}'"
```
since the clickhouse-connect doesn't try to parse the ClickHouse binding type to see if it needs milliseconds.  You could test to see if sending milliseconds regardless breaks anything and I could change that logic?

**Comment by pkit** [comment]
The code above just strips all the milliseconds.
I have opted for:
```python
from datetime import datetime, timezone

ts = datetime(2023, 6, 28, 16, 54, 41, 714000, tzinfo=timezone.utc).timestamp()
client.query(
  "SELECT {t:DateTime64(3, 'UTC')}",
  parameters={"t": int(ts * 1000)},
).result_set
```
```
[(datetime.datetime(2023, 6, 28, 16, 54, 41, 714000),)]
```

**Comment by pkit** [comment]
> I could change that logic?

I think if you will use `value.strftime('%Y-%m-%d %H:%M:%f')` it will work with or without ms/ns just fine.

**Comment by genzgd** [comment]
I suspect you're correct about the format, I'll test it with ClickHouse when I get some time.

**Comment by genzgd** [comment]
Unfortunately this breaks with a regular DateTime column:

```
Code: 53. DB::Exception: Cannot convert string 2005-06-01 13:33:00.000000 to type DateTime
```

Without knowing the column type of the parameter, I don't see a way to determine whether to add milliseconds or not.

**Comment by andnofence** [comment]
I was just bit by this issue, and I'm curious to understand if this can't be fixed. I wrote a test understand what was going on:

```
def test_query_with_timestamp_filter(clickhouse_resource):
    query = """
    with data as (
        select parseDateTime64BestEffort('2021-01-01 13:37:42.000000', 6) as t
      union all
        select parseDateTime64BestEffort('2021-01-01 13:37:42.000001', 6) as t
      union all
        select parseDateTime64BestEffort('2021-01-01 13:37:42.000002', 6) as t
      union all
        select parseDateTime64BestEffort('2021-01-01 13:37:42.000003', 6) as t
    )
    select t from data where t >= {start:DateTime64(6)} and t <= {end:DateTime64(6)}
    """
    start = datetime.fromisoformat('2021-01-01 13:37:42.000001')
    end = datetime.fromisoformat('2021-01-01 13:37:42.000002')
    result = clickhouse_resource.query_list(query, {"start": start.timestamp(), "end": end.timestamp()})
    assert len(result) == 2

def test_query_with_datetime_filter(clickhouse_resource):
    query = """
    with data as (
        select parseDateTime64BestEffort('2021-01-01 13:37:42.000000', 6) as t
      union all
        select parseDateTime64BestEffort('2021-01-01 13:37:42.000001', 6) as t
      union all
        select parseDateTime64BestEffort('2021-01-01 13:37:42.000002', 6) as t
      union all
        select parseDateTime64BestEffort('2021-01-01 13:37:42.000003', 6) as t
    )
    select t from data where t >= {start:DateTime64(6)} and t <= {end:DateTime64(6)}
    """
    start = datetime.fromisoformat('2021-01-01 13:37:42.000001')
    end = datetime.fromisoformat('2021-01-01 13:37:42.000002')
    result = clickhouse_resource.query_list(query, {"start": start, "end": end})
    assert len(result) == 2
```

The second test here fails because the connect client truncates the datetime to seconds. But what I find strange is that the query that gets sent to Clickhouse looks like this (I've removed the CTE to make it more readable):

```
SELECT t FROM data WHERE (t >= _CAST('1609508262', 'DateTime64(6)')) AND (t <= _CAST('1609508262', 'DateTime64(6)')) FORMAT Native
```

So the client does seem to be aware that I've specified DateTime64(6) for the parameter as it's doing the cast, but it has decided to only extract the seconds from the Python datetime.

The query generated for the `test_query_with_timestamp_filter` test looks like this:

```
SELECT t FROM data WHERE (t >= _CAST('1609508262.000001', 'DateTime64(6)')) AND (t <= _CAST('1609508262.000002', 'DateTime64(6)')) FORMAT Native
```

So to me it seems like the client should be able to do the same as I did in code here, if a DateTime32(N) or a DateTime64(N) is specified, simply call `timestamp()` on the `datetime`. Or am I missing something?

**Comment by genzgd** [comment]
What actual `clickhouse_connect` client function are you calling?  There's no `query_list` in the basic API.

You are correct in theory that `clickhouse_connect` could attempt to parse the type from the binding, but that would require some regex magic and is likely to be fragile.  There are also multiple workarounds listed in the previous comments.

**Comment by andnofence** [comment]
Sorry, the `query_list` method is a thin wrapper around the `query` method on the standard client. My thinking here was that since the resulting query (as pulled from `system.query_log`) is using `_CAST(..., DateTime64(6))` the client knows about the types I specified in the query. It's clearly using `timestamp()` to get the numeric value, and it must know about the parameter placeholders, so it doesn't seem any regex magic is needed? It seems like that client uses `int(dt.timestamp())` so it's just a matter of not truncating the value by using `int`?

**Comment by genzgd** [comment]
In this case it's not `clickhouse-connect` that is substituting the cast, it's the ClickHouse server.  The `{}` syntax is for server side binding, so it's ClickHouse server that is parsing the datatype and substituting query parameters.  There's some explanation of the difference here:  https://clickhouse.com/docs/en/integrations/python#parameters-argument

**Comment by genzgd** [comment]
Here's some technical details on how server side parameter binding works using the ClickHouse HTTP interface:  https://clickhouse.com/docs/en/interfaces/cli#cli-queries-with-parameters

**Comment by andnofence** [comment]
Ah, my bad! I hadn't read the docs well enough. But still, when server-side binding is used the client can decide what it sends to the server and I guess it has to do some conversion as the server can't know about the Python datatypes? So wouldn't it be possible for the client to always send over the raw `timestamp()` value instead of a string?

    select parseDateTime64BestEffort('2021-01-01 13:37:42.000001', 6) as t,  _CAST('1609504662.000001', 'DateTime64(6)') as t_from_ts;

This returns:
```
┌──────────────────────────t─┬──────────────────t_from_ts─┐
│ 2021-01-01 13:37:42.000001 │ 2021-01-01 12:37:42.000001 │
└────────────────────────────┴────────────────────────────┘
```

So it seems this would give the expected behaviour instead of the datetime value being silently truncated?

**Comment by genzgd** [comment]
Right, if you look a bit further up in the [comments](https://github.com/ClickHouse/clickhouse-connect/issues/212#issuecomment-1621580566) that breaks with a DateTime column, since ClickHouse apparently doesn't want the milliseconds in the string unless it's a Date64 type.  It becomes a choice between totally breaking DateTime bindings, or dropping milliseconds off of DateTime64 bindings.  Again since there's any easy workaround for DateTime64 (either convert to string or convert to a Unix Epoch timestamp), I think it make sense to work correctly in the more common DateTime use case. 

To truly fix this, the client would have to parse the binding strings, and as I can tell you from experience, correctly parsing ClickHouse SQL is extremely difficult at the edges.  It's probably almost reasonable to try to do something simple which would catch most use cases, but again given the workarounds, not worth the effort of adding complex and fragile parsing code.

**Comment by andnofence** [comment]
Ah, I thought that was just a problem specific to the fact that the client was passing in a string, but in trying with a numeric timestamp I see that it fails with DateTime:

```
default :) select _CAST('1609504662.000001', 'DateTime') as t_from_ts;

SELECT _CAST('1609504662.000001', 'DateTime') AS t_from_ts

Query id: d99ced90-31ac-4748-9e30-747fa89857f2


0 rows in set. Elapsed: 0.002 sec.

Received exception from server (version 23.8.2):
Code: 6. DB::Exception: Received from localhost:9000. DB::Exception: Cannot parse string '1609504662.000001' as DateTime: syntax error at position 10 (parsed just '1609504662'): While processing _CAST('1609504662.000001', 'DateTime') AS t_from_ts. (CANNOT_PARSE_TEXT)
```

But, interestingly it works if it's converted to a float first. Could the client send in the timestamp as a Float64?

```
default :) select _CAST(toFloat64('1609504662.000001'), 'DateTime'), _CAST(1609504662.000001, 'DateTime');

SELECT
    _CAST(toFloat64('1609504662.000001'), 'DateTime'),
    _CAST(1609504662.000001, 'DateTime')

Query id: 189f3fde-a00c-482c-b7fd-a0576dca2486

┌─_CAST(toFloat64('1609504662.000001'), 'DateTime')─┬─_CAST(1609504662.000001, 'DateTime')─┐
│                               2021-01-01 12:37:42 │                  2021-01-01 12:37:42 │
└───────────────────────────────────────────────────┴──────────────────────────────────────┘

1 row in set. Elapsed: 0.001 sec.
```

**Comment by genzgd** [comment]
Bound parameters are always sent as strings, because they are passed as HTTP query parameters in the URL.  The only conversion that ClickHouse will try is basically casting a String to the data type requested.

**Comment by andnofence** [comment]
Ok, I understand, then I guess there's not much to do about it. That's a shame because this is a pretty subtle issue with using datetimes. At least I learned the hard way 😅
