### ISSUE TITLE
clickhouse return error "DB::Exception: Setting http_headers_progress_interval_ms should not be changed. (SETTING_CONSTRAINT_VIOLATION)" when executing statements

### ISSUE THREAD

**Issue by walker2top** [ClickHouse/clickhouse-connect#225]
### Describe the bug

when I execute a statement, clickhouse return error "DB::Exception: Setting http_headers_progress_interval_ms should not be changed. (SETTING_CONSTRAINT_VIOLATION)" when executing statements.

<img width="1699" alt="image" src="https://github.com/ClickHouse/clickhouse-connect/assets/43695650/6fb67e00-e537-481b-a3b0-2ff5658d76a7">

I am not familiar with clickhouse. based on this, it should be that clickhouse server doesn't allow client to set "http_headers_progress_interval_ms". But I don't have any code related to this setting and it's a default behavior of this package.

if I comment out the codes which try to change this setting. the program works well.
<img width="927" alt="image" src="https://github.com/ClickHouse/clickhouse-connect/assets/43695650/0347a82d-03cc-4645-b0a0-308eaae17a7a">

<img width="904" alt="image" src="https://github.com/ClickHouse/clickhouse-connect/assets/43695650/b54c6a4d-bada-45f1-81ae-08d7be175f62">

but I find that this setting is not exposed to class or method that a developer using this package can call directly and in which we change this setting.( I am not sure about this, can correct me if I am wrong)

### Steps to reproduce
1. import package
2. connect to clickhouse server
3. execute statement

### Expected behaviour

can execute valid statement successfully by default.

if it's a default setting needed in most cases, it's also good to keep it but allow developers to decide whether program need to change these settings if needed in rare cases.

 

### Code example
```python
import clickhouse_connect

client = clickhouse_connect.get_client(
    host='xxx',
    port=443,
    username='xxxxxx',
    password='xxxxxxxxx')

print(client.server_version)
results = client.query('select 1')
print(results.result_rows)
```

#### Environment
* clickhouse-connect version:0.6.8
* Python version:3.9
* Operating system:macOS Ventura 13.3.1(a)

#### ClickHouse server
* ClickHouse Server version: vSClickhouse-22.3-011
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* Sample data for these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by genzgd** [comment]
`clickhouse-connect` automatically sets those values to prevent the underlying network connection from timing out on long queries.  Since that's very bad behavior, in most cases sending those settings should not be overridden.  If your ClickHouse administrator has made those readonly, hopefully they are set to values that will also prevent the connection from timing out.

Regardless of that, I can't reproduce this error locally on a recent ClickHouse version.  In general clickhouse-connect won't try to send that setting if it's not writeable, so I wonder if there is something in your ClickHouse version that is preventing the client from detecting the readonly state of that setting.  What package are you using?

As a workaround, after the get_client call you can override the behavior that sends those settings using "private" properties of the client:

```python
import clickhouse_connect

client = clickhouse_connect.get_client()
client._send_progress = False
client._progress_interval = 0

# Now queries should succeed

```

**Comment by walker2top** [comment]
the clickhouse service is public to many teams and it is maintained by other team so I can't know more details or change server setting until I seek help from them.

I tried your suggestion and it works well. it's good enough for me to bypass this issue. thank you! @genzgd
