### ISSUE TITLE
WARNING Connection pool is full, discarding connection: 127.0.0.1. Connection pool size: 8 (TOO_MANY_MUTATIONS)

### ISSUE THREAD

**Issue by fridary** [ClickHouse/clickhouse-connect#238]
* clickhouse: 23.7.2.25
* clickhouse-connect version: 0.6.11
* Python version: 3.9.17
* Operating system: Ubuntu 20.04.6 LTS
* Server: Intel(R) Xeon(R) CPU E5-2695 v4 @ 2.10GHz 72 cores

I made web server **nginx + gunicorn + flask + clickhouse** and getting **10+ http requests per second**, each one then send tasks to clickhouse. It starts good, but after some minutes http responses getting more and more time (like a minute), then simply error. Hardware has 72 cores, that's pretty enough to handle a lot.

gunicorn start:
`/home/fridary/miniconda3/envs/yolo/bin/gunicorn --workers 145 --worker-class=gevent --worker-connections=1000 --error-logfile /var/www/site.com/logs/gunicorn/g-error.log --bind unix:myproject.sock -m 007 wsgi:app`

Project has **index** page and **task** page. **index** gets 10+ req/second, but **task** simply executes in a loop every seond.

In **index** logs I'm getting this:
`WARNING Connection pool is full, discarding connection: 127.0.0.1. Connection pool size: 8`

In **task** logs:
```
2023-09-10 23:03:49,488 ERROR <class 'clickhouse_connect.driver.exceptions.DatabaseError'>: :HTTPDriver for http://127.0.0.1:8123 returned response code 500)
 Code: 692. DB::Exception: Too many unfinished mutations (1007) in table mydb.task (57439eaa-de08-403a-aa5e-5de99eb253d7). (TOO_MANY_MUTATIONS) (version 23.7.2.25 (official build))

2023-09-10 23:03:54,416 ERROR Traceback (most recent call last):
  File "/var/www/site.com/task.py", line 359, in <module>
    cl_client.query(f"ALTER TABLE task UPDATE executed=1 WHERE datetime >= '{tasks.result_rows[-1][7].replace(tzinfo=None)}' AND datetime <= '{tasks.result_rows[0][7].replace(tzinfo=None)}'")
  File "/home/fridary/miniconda3/envs/yolo/lib/python3.9/site-packages/clickhouse_connect/driver/client.py", line 186, in query
    response = self.command(query,
  File "/home/fridary/miniconda3/envs/yolo/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 331, in command
    response = self._raw_request(payload, params, headers, method, fields=fields)
  File "/home/fridary/miniconda3/envs/yolo/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 432, in _raw_request
    self._error_handler(response)
  File "/home/fridary/miniconda3/envs/yolo/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 357, in _error_handler
    raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: :HTTPDriver for http://127.0.0.1:8123 returned response code 500)
 Code: 692. DB::Exception: Too many unfinished mutations (1007) in table mydb.task (57439eaa-de08-403a-aa5e-5de99eb253d7). (TOO_MANY_MUTATIONS) (version 23.7.2.25 (official build))
```

So, that's very weird error, because in **task** `ALTER TABLE task UPDATE ...` simply executed every second, that's not might.
I suppose I need to change pool size for HTTPDriver. Is it correct? I did this and the same error `Connection pool size: 8`:
```
import urllib3
http = urllib3.PoolManager(num_pools=50, maxsize=100, block=False)
cl_client = clickhouse_connect.get_client(**{**db_config, **{'pool_mgr': http}})
```

**Comment by genzgd** [comment]
The warning is just a warning, it just means that a completed request/connection will not be reused.  See https://stackoverflow.com/questions/53765366/urllib3-connectionpool-connection-pool-is-full-discarding-connection.  

Your underlying problem is not with `clickhouse-connect`.  The issue is that you have 1000 update (mutations) that haven't completed on a single table in ClickHouse.   `ALTER TABLE ... UPDATE` mutations are generally relatively slow and expensive, and run asynchronously unless you change the ClickHouse setting [`mutations_sync`](https://clickhouse.com/docs/en/operations/settings/settings#mutations_sync) from the default `0` value.  So basically you are sending `ALTER TABLE ... UPDATE` statements far too quickly for ClickHouse to handle them.  Even if you have a fast machine, most mutations require rewriting several data files.

You almost certainly need to change either your data model or your "update" pipeline to do fewer mutations.  ClickHouse was originally designed for immutable data and many small updates generally don't work well.  The bottleneck on the ClickHouse server side is what is filling your connection pool, and making that connection pool bigger will almost certainly have no meaningful effect.
