### ISSUE TITLE
Client side binding is not being escaped into server timezone

### ISSUE THREAD

**Issue by aursalex** [ClickHouse/clickhouse-connect#268]
Something that I reckon when migrating from clickhouse-driver to clickhouse-connect that the datetime implementation is changed and hence the same query and paramenters yield different results. The difference is caused by the fact that clickhouse-driver replaces timezone instead of converting. Is this intended and can I have a list of breaking changes so that I didn't miss anything changes while migrating?

https://github.com/ClickHouse/clickhouse-connect/blob/0b1190942f1d13227f2d0f8f5cee9dbeefe2c0cb/clickhouse_connect/driver/query.py#L395

https://github.com/mymarilyn/clickhouse-driver/blob/db3dca27bd09a1966981f4c0b43835c117ebd1e1/clickhouse_driver/util/escape.py#L27C14-L27C14

**Comment by genzgd** [comment]
Thanks for the report!

Defining the "correct" behavior with timezones is always tricky, but I think this is just a bug.  I'll release a fix.  (Of course, my recommendation is _always_ to keep all datetime values and servers in UTC, and only convert to a local timezone when displaying to the user in a UI).

No other inconsistencies with `clickhouse-driver` have been reported, but that's a separate project and not maintained by ClickHouse Inc., so we have never validated that both drivers behave exactly the same.   That said, in general I think most things are handled the same, although it would not surprise me if there were some differences in Numpy/Pandas datatypes since those are quite convoluted.
