### ISSUE TITLE
Valuable debug info is not a part of exception message

### ISSUE THREAD

**Issue by cosinus90** [ClickHouse/clickhouse-connect#290]
I use try... except.. block to log possible errors

```
    try:
        scope.client.insert('user_data', rows_insert, column_names=keys)
    except Exception as e:
        stack_trace = traceback.format_exc()
        print(f"Error during delete/insert: {e}", stack_trace)
        logger.info(f"user_data Error: {e} {stack_trace}")     

```

It prints a message to logfile. But there is another portion that printed to console but do not go to logfile:

`Error serializing column `passport_date_issue` into data type `Nullable(Date)`
`

and as you can see - it's a crucial part for debugging for field name don't saved to the logfile.

**Comment by cosinus90** [comment]
And additionally - error message is misleading. Th column is Nullable but it's value is invalid - datetime.date(6574, 3, 23)

**Comment by genzgd** [comment]
How are you configuring your Python logging to go to a file?  That message comes from the logger defined in https://github.com/ClickHouse/clickhouse-connect/blob/main/clickhouse_connect/driver/transform.py, so I believe you need to ensure your Python configuration writes the logs from all loggers into that file.  I think the simplest way to force that is updating the `logging.basicConfig` with something like:

```python
import logging

logging.basicConfig(filename='std.log', filemode='w', format='%(name)s - %(levelname)s - %(message)s')
```

Regardless, the error is correctly being sent to the python logging system, so it is definitely possible to get the output to go to your log file with the right configuration.

As a technical matter that underlying exception does not appear in the higher level stack trace because the exception is caught when thrown by the code which converts Python objects into the ClickHouse Native format.  (The exception is then rethrown later so that it is raised by the insert call.)  As the comment in the `transform.py` file explains, the library needs to make sure that the insert fails on the ClickHouse side, not just the Python side.  Otherwise, if enough data has been sent to ClickHouse some blocks might be successfully inserted, even though the insert is halted by an error.  That's a side effect of "streaming" the insert using HTTP chunked transfer encoding, which is used to improve performance and memory usage, but it's true it makes debugging more challenging.
