### ISSUE TITLE
clickhouse playground  - Example Repositories with the most stars over one day  does not work

### ISSUE THREAD

**Issue by wasauce** [ClickHouse/clickhouse-connect#296]
From https://ghe.clickhouse.tech/#top-repositories-by-stars

There is an example "Repositories with the most stars over one day" linked here: https://ghe.clickhouse.tech/#repositories-with-the-most-stars-over-one-day

When run on the playground, the playground says there is a memory error

See attached:

![Screenshot 2024-01-27 at 8 32 29 PM](https://github.com/ClickHouse/clickhouse-connect/assets/41729/c6480ea1-49f1-4260-844e-75afb52ce788)

Playground with the query pre-added: https://play.clickhouse.com/play?user=play#U0VMRUNUCiAgICByZXBvX25hbWUsCiAgICB0b0RhdGUoY3JlYXRlZF9hdCkgQVMgZGF5LAogICAgY291bnQoKSBBUyBzdGFycwpGUk9NIGdpdGh1Yl9ldmVudHMKV0hFUkUgZXZlbnRfdHlwZSA9ICdXYXRjaEV2ZW50JwpHUk9VUCBCWQogICAgcmVwb19uYW1lLAogICAgZGF5Ck9SREVSIEJZIGNvdW50KCkgREVTQwpMSU1JVCAxIEJZIHJlcG9fbmFtZQpMSU1JVCA0MA==

**Comment by genzgd** [comment]
I've asked our team (including Alexey Milovidov, the ClickHouse CTO and author of that article) to take a look.  My first guess is that the size of the `github_events` table has increased significantly since 2020 and the server hosting play.clickhouse.com no longer can handle some queries from larger db, but I'll see what we find.

If I don't get an answer in the next couple of days I'll move this issue to the main `ClickHouse` repository, since it doesn't seem related to `clickhouse_connect` :)

**Comment by genzgd** [comment]
Alexey confirmed it's because in the increase in data since 2020.

If you limit the query by year, it should work as expected:

```sql
SELECT
    repo_name,
    toDate(created_at) AS day,
    count() AS stars
FROM github_events
WHERE event_type = 'WatchEvent' and toYear(created_at) >= 2023
GROUP BY
    repo_name,
    day
ORDER BY count() DESC
LIMIT 1 BY repo_name
LIMIT 50

```
  We'll probably update the article at some point.

**Comment by wasauce** [comment]
@genzgd thank you very much - I really appreciate you digging in to this. The github dataset is a wonderful resource, and the guide is quite helpful for learning Clickhouse. 

I apologize I put this issue in the wrong place.
