### ISSUE TITLE
FixedString values are returned as bytes

### ISSUE THREAD

**Issue by pofl** [ClickHouse/clickhouse-connect#325]
### Describe the bug

FixedString is returned as bytes

### Expected behaviour

FixedString is returned as string

### Code example
```python
client.query_arrow("select 'ab'::FixedString(2) as iamnotastr")
pyarrow.Table
iamnotastr: fixed_size_binary[2] not null
----
iamnotastr: [[6162]]
```
```python
client.query_df("select 'ab'::FixedString(2) as iamnotastr")
  iamnotastr
0      b'ab'
```
```python
client.query("select 'ab'::FixedString(2) as iamnotastr").result_rows
[(b'ab',)]
```

#### Environment
* clickhouse-connect version: clickhouse-connect==0.7.3
* Python version: 3.12.2
* Operating system: Linux

#### ClickHouse server
* ClickHouse Server version: 23.12.3.40

**Comment by genzgd** [comment]
ClickHouse treats both Strings and FixedStrings as raw strings of bytes, and it is generally up to the client/consumer whether (and how) to encode that data to strings or otherwise.  In `clickhouse-connect`, the default output format for FixedString is bytes, but it can be changed using read formats.   See the [documentation](https://clickhouse.com/docs/en/integrations/python#read-formats).

Note that a different set of ClickHouse settings controls how `query_arrow` or `query_arrow_stream` results are returned, as these are managed on the server side.  These can be added when calling `query_arrow`.  See the ClickHouse [documentation](https://clickhouse.com/docs/en/interfaces/format) for a list of possible settings.
