### ISSUE TITLE
cannot  upload Python NaN or None  to clickhouse NULL (nullable columns)

### ISSUE THREAD

**Issue by a819721810** [ClickHouse/clickhouse-connect#345]
**Is your feature request related to a problem? Please describe.**
use pandas dataFrame,  NaN or None insert into clickhouse table ,  cannot transfer NULL

**Additional context**

```
CREATE TABLE user_4.test_local on cluster cb_cluster
(
     `code` String ,
    `open` Nullable(Float64),

)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{uuid}/{shard}',
 '{replica}')
 PRIMARY KEY code
SETTINGS index_granularity = 8192
```
![image](https://github.com/ClickHouse/clickhouse-connect/assets/10041362/a7a65532-75f3-438f-9814-719107486f2d)

![image](https://github.com/ClickHouse/clickhouse-connect/assets/10041362/e227a6be-d927-4c36-8d53-57cc66221cd7)

i have to exec:
`alter table user_4.test_local on cluster cb_cluster update open = null where isNaN(open)`

**Comment by genzgd** [comment]
It looks like you are using `chdb`, not `clickhouse_connect`.

Regardless, the issue is that pandas itself is automatically converting the `None` values into a `nan` before you insert the dataframe.  (I believe this is the default behavior in recent versions of pandas).  Notice that when you `print(df)`, the value is NaN (and it's not changed by the upload). 

To insert nulls into ClickHouse, I think you'll need to explicitly change the change the dtype of the 'open' column from `float` to object.  In `clickhouse_connect`, this will result in both None and `np.nan` being inserting as ClickHouse nulls, I don't know what the behavior is in chdb, since that is a completely different project.

Here's my example code for clickhouse_connect:

```python
import clickhouse_connect
import pandas as pd
import numpy as np

client = clickhouse_connect.create_client(port=8423)
client.command('DROP TABLE IF EXISTS test_local')
client.command(
    """
    CREATE TABLE test_local
    (
        `code` String,
        `open` Nullable(Float64),
    
    )
    ENGINE = MergeTree ORDER BY code
    """)

data = {
    'code': ['AAPL', 'GOOGL', 'MSFT', 'AMZN'],
    'open': [135.0, np.nan, 150.0, None]
}
df = pd.DataFrame(data)
df['open'] = df['open'].astype('object')
client.insert_df('test_local', df)
```

Another possible approach is to use Nullable(Decimal) or Nullable(Int32) columns in ClickHouse (where the Int value would represent cents, not dollars).

**Comment by genzgd** [comment]
`use_none` only applies to SELECT queries, not inserts.  Even if it applied to inserts, the Pandas value is already a NaN in your case so `use_none` wouldn't matter.  There in theory could be another option like "insert NaN as NULL" for nullable columns, but that would basically require the library to do the same thing you already can do before you call insert -- which is change the dtype of the dataframe to `object`.
