### ISSUE TITLE
Streaming results question

### ISSUE THREAD

**Issue by mkhatuntcov** [ClickHouse/clickhouse-connect#35]
I am looking for an opportunity to select many rows over HTTP similar to `clickhouse-driver`:

https://clickhouse-driver.readthedocs.io/en/latest/quickstart.html#streaming-results

and according the documentation:

https://github.com/clickhouse/clickhouse-connect#http-client-constructorinitialization-parameters

```
query_limit:int LIMIT value added to all queries.
Defaults to 5,000 rows. Unlimited queries are not supported to prevent crashing the driver
```

As far as  far as I learned there is no way to do it with `clickhouse-connect`  Let me know if I missing something.

Thank you and have a nice day.

**Comment by genzgd** [comment]
The documentation is somewhat incorrect.  Unlimited queries are not supported by default, but you can enable them by settings `query_limit=0`, understanding that the entire dataset will be loaded into memory.

At this time ClickHouse Connect does not support a streaming model, in part because the ClickHouse HTTP interface is HTTP 1.1 and does not support HTTP 2.0 streaming semantics.  Streaming/event driven response process is on the roadmap; however it's not certain how soon it will be supported.

**Comment by mkhatuntcov** [comment]
thanks for the answer!

**Comment by genzgd** [comment]
Streaming queries have been implemented, and work pretty fast.  https://clickhouse.com/docs/en/integrations/language-clients/python/queries#streaming-queries
