### ISSUE TITLE
How to get http chunk size?

### ISSUE THREAD

**Issue by Bikbai** [ClickHouse/clickhouse-connect#372]
My requests are periodically timed out, as reslt not all data was inserted into DB. Im loading in my home hardware some data, so i've got this result
```
Request key     Total inserted
2019-01-20	100000 -- request completed
2019-01-21	33388   -- request timeout
2019-01-22	66612   -- request timeout
```
Little worrying about it - how to hande portions? For example, set portion to all data, to avoid corruption.

**Comment by genzgd** [comment]
What is the timeout error you are getting?  There are many types of timeouts when inserting data in ClickHouse

You can increase increase the `send_receive_timeout` paramete when calling `get_client` (the default is 5 minutes), but in most cases that shouldn't be necessary.

**Comment by Bikbai** [comment]
Stack trace:

```
  File "C:\Python312\Lib\site-packages\clickhouse_connect\driver\httpclient.py", line 434, in _raw_request
    raise OperationalError(f'Error {ex} executing HTTP request attempt {attempts}{err_url}') from ex
clickhouse_connect.driver.exceptions.OperationalError: Error ('Connection aborted.', TimeoutError('timed out')) executing HTTP request attempt 1
```
BTW the task is not to increase timeout, my goal - not to get corrupted data in DB.

**Comment by genzgd** [comment]
If your inserts are just taking a long time, then you may just need a less data or a more powerful ClickHouse server (more CPU cores and memory).

I can't tell you how to break up the data you are inserting -- it depends where it is coming from.  If it's pandas you can use iloc to split it -- see https://stackoverflow.com/questions/41624241/pandas-split-dataframe-into-two-dataframes-at-a-specific-column.  If it's some other array, you can do something similar with just array slices:

```python

chunk1 = chunk[1000:]
chunk2= chunk[:1000]
```

Note that splitting DataFrames or arrays like that can be slow and take a lot of memory.

In any case I'm going to close this because that's really Python programming and not related to clickhouse-connect functionality.

**Comment by Bikbai** [comment]
eh. In my situation, clickhouse-connect functionality executes my batch partially - thats the point. 

In productive environment i dont want to see my requests executed by random percent. Best scenario is "whole or nothing"

**Comment by genzgd** [comment]
Well clickhouse-connect returns an error if you time out.  It's the application's responsibility to retry after errors; normally database drivers will not automatically retry because the user needs to make that decision based on the error.  For example, if your user has been deleted or the network is down, you wouldn't want the driver to retry forever.
