### ISSUE TITLE
Incorrect Handling of UInt64 Data Type

### ISSUE THREAD

**Issue by mikezsin** [ClickHouse/clickhouse-connect#379]
### Describe the bug
UInt64 in ClickHouse is an unsigned 64-bit integer with a range of [0, 18446744073709551615], and should not be represented as negative values.
The arr_type variable is set to 'q' (signed) if fmt is 'signed'. For UInt64, which is inherently unsigned, it should always use 'Q' regardless of the format. Using 'q' can incorrectly interpret the data as signed, leading to negative values.

### Steps to reproduce
SELECT toUInt64('9400017615393847655') in Superset

### Code example
```python
#clickhouse-connect/clickhouse_connect/datatypes/numeric.py
class UInt64(ArrayType):
    valid_formats = 'signed', 'native'
    _array_type = 'Q'
    np_type = '<u8'
    python_type = int

    def _read_column_binary(self, source: ByteSource, num_rows: int, ctx: QueryContext):
        fmt = self.read_format(ctx)
        if ctx.use_numpy:
            np_type = '<q' if fmt == 'signed' else '<u8'
            return numpy_conv.read_numpy_array(source, np_type, num_rows)
        arr_type = 'q' if fmt == 'signed' else 'Q' # why signed?  https://clickhouse.com/docs/en/sql-reference/data-types/int-uint
        return source.read_array(arr_type, num_rows)

```

**Comment by genzgd** [comment]
This might be possible in later versions of Superset, but this code was specifically implemented for Superset compatibility.  Superset tries to convert UInt64 values into PyArrow Int64Array and it would return aan error "Python int too large to convert to C long,"  There are some details in https://github.com/apache/superset/issues/15876.

If current versions of Superset actually works correctly with large UInt64 values then the default format for UInt64 types  can be changed or removed here:  https://github.com/apache/superset/blob/master/superset/db_engine_specs/clickhouse.py#L234-L235.  If you can validate it works, please open an appropriate issue/PR in Superset itself, as this is not something that can be fixed in the `clickhouse-connect` code.
