### ISSUE TITLE
How to appropriate pass values ?

### ISSUE THREAD

**Issue by Andrew32bit** [ClickHouse/clickhouse-connect#38]
I have
 paramaters={'hash_id':hash_id,'tbl_name':tbl_name}
and query like
client.query('select %s from %s',parameters)
And error : TypeError: not enough arguments for format string

**Comment by genzgd** [comment]
The parameterized queries require the Python "dictionary" format for the query string, so something like

```
SELECT %(hash_id)s FROM %(tbl_name)s
```

will prevent the TypeError.  However, the driver doesn't actually support using parameters to set table or column names, so that query may not work.  The supported use case is for actual values, like this:

```
SELECT * FROM some_table WHERE hash_id = %(hash_id)s AND date >= %(some_date)s
```

Just for an FYI while looking into this question I found a bug with formatting `datetime` values which will be fixed in the next release.

**Comment by Andrew32bit** [comment]
Thank you!
