### ISSUE TITLE
Clickhouse 24.08 JSON Support

### ISSUE THREAD

**Issue by patrizok** [ClickHouse/clickhouse-connect#398]
#### Environment
* clickhouse-connect version:0.7.19
* Python version: 3.12.5
* Operating system: Docker - Ubuntu
* ClickHouse Server version: 24.8.4.13
### Code example
```python
import clickhouse_connect

client = clickhouse_connect.get_client(host='x.x.x.x', username='xxx', password='xxx')

result = client.query('''SELECT
    json.type.name,
    count() AS count
FROM events
GROUP BY ALL
ORDER BY count DESC
LIMIT 10
''')
res = result.result_rows
pass
```

#### Problem:
clickhouse_connect does not support new features released 24.8
You can get detailed information from here: https://clickhouse.com/blog/clickhouse-release-24-08

Thanks

**Comment by genzgd** [comment]
Experimental feature available in 0.8.0

**Comment by genzgd** [comment]
@niyue Does Arrow support something like a semi-structured column?  I'm not an expert but in any case it would require ClickHouse server support.

**Comment by genzgd** [comment]
`clickhouse-connect` also supports reading and writing JSON as a String, but that's only when using Native format.  The Arrow functionality would have to be implemented in ClickHouse itself, since the ClickHouse server is ultimately responsible for serializing/deserializing all of the `clickhouse-connect` client `arrow` functions.
