### ISSUE TITLE
get_client arg apply_server_timezone=False not working

### ISSUE THREAD

**Issue by JohnorJohnny** [ClickHouse/clickhouse-connect#410]
### Describe the bug
I'm trying NOT to use the server's time zone. Timezone on server is Europe/Moscow, but i'm using UTC in my program.
So when I'm trying to send datetime values clickhouse_connect trying to convert values into server tz even if apply_server_timezone=False.

### Expected behaviour
Code should return table

### Code example
```python
import clickhouse_connect
import pandas as pd

client = clickhouse_connect.get_client(
    host='...',
    username='...',
    password='...',
    apply_server_timezone=False,
)
query = """
SELECT *
FROM sales_dynamics
WHERE `period` >= %s
"""
cols = client.query_df(query, parameters=(pd.Timestamp("2024-06-01"),))
```
This code raise an error from function `format_query_value(...)`:
```
TypeError: Cannot convert tz-naive Timestamp, use tz_localize to localize
```
I'm not sure but I think somthhing went wrong in client.py file in `_init_common_settings(...)` func

#### Environment
* clickhouse-connect version: 0.8.3
* Python version: 3.12
* Operating system: windows 10

**Comment by genzgd** [comment]
I can't reproduce this.  What ClickHouse version are you using?  What line is raising the TypeError?

**Comment by genzgd** [comment]
So a few of things.

- pd.Timestamps aren't officially supported for query binding.  Use a Python datetime.datetime, which supports the astimezone method even for naive datetimes, while a pandas Timestamp uses tz_localize if the Timestamp is naive.  The query binding code should not have to check for any pandas types.

- `apply_server_timezone` only affects returned datetime values from a query, it doesn't affect parameter binding.  That because ClickHouse will always interpret a query parameter based on its own timezone, so any time *should* be converted to the server's timezone.

- If you are filtering on a DateTime column, the simplest workaround is to send a datetime value with a UTC timezone instead of a naive value.  

- In this particular case, depending on the data type of `period`, you should probably send a Python datetime.date object, not a datetime.datetime object.
