### ISSUE TITLE
Unexpected Decimal Rounding when Transferring Data from PyArrow to ClickHouse

### ISSUE THREAD

**Issue by andras-matter** [ClickHouse/clickhouse-connect#435]
### Describe the bug
There is a floating point number in python, which is rounded, so that it has 4 decimal digits. This number "lives" in a PyArrow Table, and, when using `clickhouse_connect.insert_arrow()`, the inserted number is different from the one in the PyArrow Table.
### Steps to reproduce
1. Run clickhouse server
2. Run code example

### Expected behaviour
If the values (before sinking the data) have 4 fractional digits, and the table column have 4 fractional digits, the values remain the same.
### Code example
```python
import clickhouse_connect
import pyarrow

data = pyarrow.Table.from_pylist([{"value": 0.0012}])

client = clickhouse_connect.get_client(
    username="default",
    password="",
    host="localhost",
    port=8123,
    send_receive_timeout=1000,
    connect_timeout=1000,
)

client.command(
    """
    CREATE TABLE IF NOT EXISTS test (
        value Nullable(Decimal64(4))
    ) ENGINE = MergeTree
    ORDER BY tuple();
"""
)

client.insert_arrow(table="test", arrow_table=data)

print(client.query("select * from test").result_columns)
```

#### Environment
* clickhouse-connect version: 0.8.7
* Python version: 3.12
* Operating system: Linux and MacOS

#### ClickHouse server
* ClickHouse Server version: tested on 24.6 and 24.11
* `CREATE TABLE` statements for tables involved: ```
CREATE TABLE IF NOT EXISTS test (
        value Nullable(Decimal64(4))
    ) ENGINE = MergeTree
    ORDER BY tuple();
```

**Comment by genzgd** [comment]
I think your problem is with Float conversion.   I believe this line creates a list of Arrow Double values:

```python
data = pyarrow.Table.from_pylist([{"value": 0.0012}])
```

A PyArrow Double is an IEEE Float64, and there can be precision loss when converting from a Float value to a ClickHouse Decimal value.  So you should either use a Decimal Arrow value or a Float64 ClickHouse column.

In any case this is handled either by the Arrow Library or the ClickHouse server interpreting Arrow format, and can't be modified within the `clickhouse-connect` library.
