### ISSUE TITLE
Streaming queries buffering?

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/clickhouse-connect#99]
It would be great to understand how exactly streaming interface is behaving in clickhouse-connect

Does it request next block from clickhouse-server on iteration over stream_column_blocks()?
If so, it's possible to have some buffer of preloaded blocks in client memory and have some setting to control size of such buffer in rows/blocks numbers.

**Comment by genzgd** [comment]
Everything is happening the context of a single HTTP request.  Data is read from the request body stream block by block (native format.). Currently the transform "preloads" the first block since that will have column names and types.  It would be fairly easy to configure the number of preloaded blocks or rows by adding a buffer of blocks in the transform module, rather than just the first block.  https://github.com/ClickHouse/clickhouse-connect/blob/097415b998133db143ae63fc541a7e506e6ff357/clickhouse_connect/driver/transform.py#L44-L54

I'm not sure how useful that would be though?

**Comment by UnamedRus** [comment]
> I'm not sure how useful that would be though?

Well, it was first question of one of our clients when we consider looking in new clickhouse-connect driver.

We can imagine some use case, when you need to do some calculations based for all data related to specific user. (you are receiving dataset ~sorted by user_id)       
So you need to keep consuming blocks until user_id will switch to another value and only after this do processing.

**Comment by genzgd** [comment]
> So you need to keep consuming blocks until user_id will switch to another value and only after this do processing.

That seems like it would be fairly easy to do in application code rather than building into the driver.
